package view;

import access.usuarioDAO;
import model.contenidoModel;
import access.contenidoDAO;
import java.util.ArrayList;
import javax.swing.JButton;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

public class contenido extends javax.swing.JFrame {
    
    public static contenidoModel feedbackContenido;
    public static String nombreAutor;
    JButton btnTable = new JButton("Entrar");

    public contenido() {
        initComponents();
        
        // Ponemos el nombre del usuario como bienvenida
        nombreUsuario.setText(login.loginUser.getNombreUsuario());

        // Poner la ventana en la mitad de la pantalla
        this.setLocationRelativeTo(null);

        // Si el usuario no es creador (Director) no le hacemos visible el boton de crear contenido
        if(!login.loginUser.isDirectorUsuario()){
            createContent.setVisible(false);
        }
        
        // Render para colocar botones en la tabla
        results.setDefaultRenderer(Object.class, new Render());
        results.setRowHeight(25);
        
        // Creamos un modelo de la tabla para modificarla
        DefaultTableModel modelo = (DefaultTableModel) results.getModel();
        
        contenidoDAO initialData = new contenidoDAO();
        ArrayList<ArrayList> result = initialData.getAllContent();
        
        // Llenamos la tabla
        for(int i = 0; i < result.size(); i++){
            ArrayList<ArrayList> row = result.get(i);
            modelo.addRow(new Object[]{row.get(4), row.get(0), row.get(1), row.get(2), row.get(3), btnTable});
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        contentMessage = new javax.swing.JLabel();
        createContent = new javax.swing.JButton();
        welcomeMessage = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JLabel();
        resultsMessage = new javax.swing.JLabel();
        filterButton = new javax.swing.JButton();
        filterString = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        results = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        contentMessage.setForeground(new java.awt.Color(255, 255, 255));
        contentMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        contentMessage.setText("Contenido recomendado");

        createContent.setText("Crear");
        createContent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createContentMouseClicked(evt);
            }
        });

        welcomeMessage.setForeground(new java.awt.Color(255, 255, 255));
        welcomeMessage.setText("Bienvenido, ");

        nombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        nombreUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreUsuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(contentMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 626, Short.MAX_VALUE)
                .addComponent(createContent)
                .addGap(18, 18, 18)
                .addComponent(welcomeMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contentMessage)
                    .addComponent(createContent)
                    .addComponent(welcomeMessage)
                    .addComponent(nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        resultsMessage.setText("Resultados");

        filterButton.setText("Buscar");
        filterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filterButtonMouseClicked(evt);
            }
        });

        results.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Autor", "Titulo", "Descripción", "Categoria", "Produccion", "Leer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        results.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(results);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(resultsMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filterString, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filterButton)))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultsMessage)
                    .addComponent(filterButton)
                    .addComponent(filterString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createContentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createContentMouseClicked
   
        crearContenido createContent = new crearContenido();
        createContent.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_createContentMouseClicked

    private void filterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filterButtonMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) results.getModel();

        int rowCount = modelo.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        
        String filter = filterString.getText();
        contenidoDAO initialData = new contenidoDAO();
        
        if("".equals(filter)){
            ArrayList<ArrayList> result = initialData.getAllContent();
            for(int i = 0; i < result.size(); i++){
                ArrayList<ArrayList> row = result.get(i);
                modelo.addRow(new Object[]{row.get(4), row.get(0), row.get(1), row.get(2), row.get(3), btnTable});
            }
        } else {
            ArrayList<ArrayList> result = initialData.getFliterContent(filter);
            
            if(result.isEmpty()){
                modelo.addRow(new Object[]{"Sin resultados", "Sin resultados", "Sin resultados", "Sin resultados", "Sin resultados", "Sin resultados"});
            }
            else {
                for(int i = 0; i < result.size(); i++){
                    ArrayList<ArrayList> row = result.get(i);
                    modelo.addRow(new Object[]{row.get(4), row.get(0), row.get(1), row.get(2), row.get(3), btnTable});
                }
            }
        }
        
    }//GEN-LAST:event_filterButtonMouseClicked

    private void resultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultsMouseClicked
        int column = results.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/results.getRowHeight();
                
        if(column == 5){
            DefaultTableModel resultsModel = (DefaultTableModel) results.getModel();
            
            String autor = String.valueOf(resultsModel.getValueAt(row, 0));
            String titulo = String.valueOf(resultsModel.getValueAt(row, 1));
            String descripcion = String.valueOf(resultsModel.getValueAt(row, 2));
            String categoria = String.valueOf(resultsModel.getValueAt(row, 3));
            String produccion = String.valueOf(resultsModel.getValueAt(row, 4));
            
            usuarioDAO consultId = new usuarioDAO();
            int id = consultId.getIdUser(titulo, descripcion, categoria, produccion);
            
            feedbackContenido = new contenidoModel(titulo, descripcion, categoria, produccion, id);
            nombreAutor = autor;
                    
            feedback showFeedback = new feedback();
            showFeedback.setVisible(true);
            this.setVisible(false);
            

        }else{
            System.out.println("No le dio en un boton");
        }
    }//GEN-LAST:event_resultsMouseClicked

    private void nombreUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreUsuarioMouseClicked
        account account = new account();
        account.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nombreUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(contenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(contenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(contenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(contenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new contenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contentMessage;
    private javax.swing.JButton createContent;
    private javax.swing.JButton filterButton;
    private javax.swing.JTextField filterString;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JTable results;
    private javax.swing.JLabel resultsMessage;
    private javax.swing.JLabel welcomeMessage;
    // End of variables declaration//GEN-END:variables
}
