package view;

import static javax.swing.JOptionPane.showMessageDialog;
import model.usuarioModel;
import model.contenidoModel;
import access.contenidoDAO;

public class crearContenido extends javax.swing.JFrame {

    public crearContenido() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        messageCreateContent = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        titleMessage = new javax.swing.JLabel();
        tituloContenido = new javax.swing.JTextField();
        categoryMessage = new javax.swing.JLabel();
        categoriaContenido = new javax.swing.JComboBox<>();
        productionMessage = new javax.swing.JLabel();
        tipoContenido = new javax.swing.JComboBox<>();
        descripcionMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionContenido = new javax.swing.JTextArea();
        publicarContenido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        messageCreateContent.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        messageCreateContent.setForeground(new java.awt.Color(255, 255, 255));
        messageCreateContent.setText("Publicación de contenido");

        backButton.setText("Volver");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(messageCreateContent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageCreateContent)
                    .addComponent(backButton))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        titleMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        titleMessage.setText("Titulo");

        categoryMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        categoryMessage.setText("Categoria");

        categoriaContenido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciencia ficción", "Terror", "Acción", "Realista", "Aventura", "Comedia", "Otro" }));

        productionMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        productionMessage.setText("De que se trata");

        tipoContenido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Serie", "Pelicula", "Cortometraje", "Largometraje", "Blog", "Libro", "Otro" }));

        descripcionMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        descripcionMessage.setText("Descripción");

        descripcionContenido.setColumns(20);
        descripcionContenido.setRows(5);
        jScrollPane1.setViewportView(descripcionContenido);

        publicarContenido.setText("Publicar");
        publicarContenido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        publicarContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                publicarContenidoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleMessage)
                            .addComponent(tituloContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(173, 173, 173)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryMessage)
                            .addComponent(categoriaContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productionMessage)
                            .addComponent(tipoContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(200, 200, 200))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(publicarContenido)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(descripcionMessage)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 913, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(55, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleMessage)
                    .addComponent(categoryMessage)
                    .addComponent(productionMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(descripcionMessage)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(publicarContenido)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void publicarContenidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_publicarContenidoMouseClicked
        // Obtenemos los valores del contenido que quiera dar el usuario
        String titulo = tituloContenido.getText();
        String descripcion = descripcionContenido.getText();
        String categoria = (String) categoriaContenido.getSelectedItem();
        String tipo = (String) tipoContenido.getSelectedItem();
        
        // Creamos un nuevo modelo con el cual subiremos los datos a la BD
        contenidoModel contentModel = new contenidoModel(titulo, descripcion, categoria, tipo, login.loginUser.getIdUsuario());
        contenidoDAO createContent = new contenidoDAO();
        
        // Si obtenemos que se modifico la base de datos le mandamos un mensaje al usuario
        boolean pass = createContent.createContent(contentModel);
        
        if(pass){
            showMessageDialog(null, "Contenido creado correctamente");

            contenido content = new contenido();
            content.setVisible(true);
            this.setVisible(false);
            
        } else {
            showMessageDialog(null, "Algo salio mal en la creacion");
        }
        
        
    }//GEN-LAST:event_publicarContenidoMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        contenido content = new contenido();
        content.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crearContenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> categoriaContenido;
    private javax.swing.JLabel categoryMessage;
    private javax.swing.JTextArea descripcionContenido;
    private javax.swing.JLabel descripcionMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageCreateContent;
    private javax.swing.JLabel productionMessage;
    private javax.swing.JButton publicarContenido;
    private javax.swing.JComboBox<String> tipoContenido;
    private javax.swing.JLabel titleMessage;
    private javax.swing.JTextField tituloContenido;
    // End of variables declaration//GEN-END:variables
}
