package view;

import access.contenidoDAO;
import model.reseñaModel;
import access.reseñaDAO;
import access.usuarioDAO;
import java.util.ArrayList;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

public class feedback extends javax.swing.JFrame {

    public feedback() {
        initComponents();
        this.setLocationRelativeTo(null);
        tituloValue.setText(contenido.feedbackContenido.getTituloContenido());
        descripcionValue.setText(contenido.feedbackContenido.getDescripcionContenido());
        categoriaValue.setText(contenido.feedbackContenido.getCategoriaContenido());
        produccionValue.setText(contenido.feedbackContenido.getProduccionContenido());
        autorValue.setText(contenido.nombreAutor);
        
        calificacionReseña.setPaintTicks(true); //las rayitas que marcan los números
        calificacionReseña.setMajorTickSpacing(1); // de cuanto en cuanto los números en el slider
        calificacionReseña.setPaintLabels(true);
        
        DefaultTableModel modelo = (DefaultTableModel) tableReviews.getModel();
        contenidoDAO idContent = new contenidoDAO();
        int id = idContent.getIdContent(contenido.feedbackContenido.getTituloContenido(), contenido.feedbackContenido.getDescripcionContenido(), contenido.feedbackContenido.getCategoriaContenido(), contenido.feedbackContenido.getProduccionContenido());
        reseñaDAO reseña = new reseñaDAO();
        ArrayList<ArrayList> result = reseña.getAllReviews(id);
        
        if(result.isEmpty()){
            modelo.addRow(new Object[]{"Sin resultados", "Sin resultados", "Sin resultados"});
        } else {
            for(int i = 0; i < result.size(); i++){
                ArrayList<ArrayList> row = result.get(i);
                modelo.addRow(new Object[]{row.get(0), row.get(1), row.get(2)});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoriaContenido = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tituloValue = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        categoriaMessage = new javax.swing.JLabel();
        produccionMessage = new javax.swing.JLabel();
        autorMessage = new javax.swing.JLabel();
        descripcionMessage = new javax.swing.JLabel();
        jScrollPanel2 = new javax.swing.JScrollPane();
        feedbackUser = new javax.swing.JTextArea();
        feedbackMessage = new javax.swing.JLabel();
        publicarContenido = new javax.swing.JButton();
        contactarAutor = new javax.swing.JButton();
        comentariosMessage = new javax.swing.JLabel();
        categoriaValue = new javax.swing.JLabel();
        produccionValue = new javax.swing.JLabel();
        autorValue = new javax.swing.JLabel();
        descripcionValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReviews = new javax.swing.JTable();
        calificacionReseña = new javax.swing.JSlider();
        calificacionMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        categoriaContenido.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        tituloValue.setForeground(new java.awt.Color(255, 255, 255));
        tituloValue.setText("Titulo contenido");

        back.setText("Volver");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(tituloValue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloValue)
                    .addComponent(back))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        categoriaMessage.setText("Categoria:");

        produccionMessage.setText("Se trata de: ");

        autorMessage.setText("Autor: ");

        descripcionMessage.setText("Descripcion");

        feedbackUser.setColumns(20);
        feedbackUser.setLineWrap(true);
        feedbackUser.setRows(4);
        feedbackUser.setAutoscrolls(false);
        jScrollPanel2.setViewportView(feedbackUser);

        feedbackMessage.setText("Feedback");

        publicarContenido.setText("Publicar");
        publicarContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                publicarContenidoMouseClicked(evt);
            }
        });

        contactarAutor.setText("Contactar");
        contactarAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactarAutorMouseClicked(evt);
            }
        });

        comentariosMessage.setText("Otros comentarios");

        descripcionValue.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tableReviews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Calificación", "Descipción", "Autor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableReviews);

        calificacionReseña.setMaximum(5);

        calificacionMessage.setText("Calificación");

        javax.swing.GroupLayout categoriaContenidoLayout = new javax.swing.GroupLayout(categoriaContenido);
        categoriaContenido.setLayout(categoriaContenidoLayout);
        categoriaContenidoLayout.setHorizontalGroup(
            categoriaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(categoriaContenidoLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(categoriaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoriaContenidoLayout.createSequentialGroup()
                        .addGroup(categoriaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                            .addComponent(descripcionValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(categoriaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(categoriaContenidoLayout.createSequentialGroup()
                                .addGroup(categoriaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calificacionMessage)
                                    .addComponent(calificacionReseña, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 48, Short.MAX_VALUE)
                                .addComponent(publicarContenido)
                                .addGap(53, 53, 53)
                                .addComponent(contactarAutor))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoriaContenidoLayout.createSequentialGroup()
                        .addGroup(categoriaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(feedbackMessage)
                            .addComponent(descripcionMessage)
                            .addGroup(categoriaContenidoLayout.createSequentialGroup()
                                .addComponent(categoriaMessage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(categoriaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(165, 165, 165)
                                .addComponent(produccionMessage)
                                .addGap(38, 38, 38)
                                .addComponent(produccionValue, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addGroup(categoriaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(categoriaContenidoLayout.createSequentialGroup()
                                .addComponent(autorMessage)
                                .addGap(44, 44, 44)
                                .addComponent(autorValue, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comentariosMessage))
                        .addGap(67, 67, 67))))
        );
        categoriaContenidoLayout.setVerticalGroup(
            categoriaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriaContenidoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(categoriaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaMessage)
                    .addComponent(produccionMessage)
                    .addComponent(autorMessage)
                    .addComponent(categoriaValue)
                    .addComponent(produccionValue)
                    .addComponent(autorValue))
                .addGap(18, 18, 18)
                .addGroup(categoriaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionMessage)
                    .addComponent(comentariosMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(categoriaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(descripcionValue, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addGroup(categoriaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feedbackMessage)
                    .addComponent(calificacionMessage))
                .addGroup(categoriaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(categoriaContenidoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(categoriaContenidoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(categoriaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calificacionReseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(categoriaContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(publicarContenido)
                                .addComponent(contactarAutor)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoriaContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoriaContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactarAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactarAutorMouseClicked
        reseñaDAO reseña = new reseñaDAO();
        usuarioDAO usuario = new usuarioDAO(); 
        
        String titulo = contenido.feedbackContenido.getTituloContenido();
        String descripcion = contenido.feedbackContenido.getDescripcionContenido();
        String categoria = contenido.feedbackContenido.getCategoriaContenido();
        String produccion= contenido.feedbackContenido.getProduccionContenido();
        
        int idUsuario = usuario.getIdUser(titulo, descripcion, categoria, produccion);
        
        boolean pass = usuario.shareEmail(idUsuario);
        System.out.println(idUsuario);

        if(pass){
           String emailUser = reseña.getContactUser(idUsuario); 
           showMessageDialog(null, "El correo del usuaio es " + emailUser);    

        } else {
            showMessageDialog(null, "El usuario no tiene permitido compartir su contacto");    
        }
        
    }//GEN-LAST:event_contactarAutorMouseClicked

    private void publicarContenidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_publicarContenidoMouseClicked
        // Accedemos a los valores de los campos 
        String reseñaContenido = feedbackUser.getText();
        float calificacionContenido = calificacionReseña.getValue();
        
        // Accedemos a el id del contenido al cual le queremos hacer una reseña
        contenidoDAO idContent = new contenidoDAO();
        int id = idContent.getIdContent(contenido.feedbackContenido.getTituloContenido(), contenido.feedbackContenido.getDescripcionContenido(), contenido.feedbackContenido.getCategoriaContenido(), contenido.feedbackContenido.getProduccionContenido());
        
        // Creamos un nuevo modelo de reseña con la cual haremos una insercion en la base de datos
        reseñaModel reseña = new reseñaModel(calificacionContenido, reseñaContenido, id ,login.loginUser.getIdUsuario());
        reseñaDAO createReview = new reseñaDAO();
        
        // Insertamos la reseña en la base de datos
        createReview.createReview(reseña);
        
        // Eliminamos los registros que tengamos en la tabla
        DefaultTableModel modelo = (DefaultTableModel) tableReviews.getModel();
        int rowCount = modelo.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        
        // Volvemos a llamar a la tabla para que aparesca nuestra review
        reseñaDAO reseñaDAO = new reseñaDAO();
        ArrayList<ArrayList> result = reseñaDAO.getAllReviews(id);
        
        for(int i = 0; i < result.size(); i++){
            ArrayList<ArrayList> row = result.get(i);
            modelo.addRow(new Object[]{row.get(0), row.get(1), row.get(2)});
        }
        
        // Motramos un mensaje de que la reseña se creo correctamente
        showMessageDialog(null, "La reseña se creo correctamente");

    }//GEN-LAST:event_publicarContenidoMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        contenido showContenido = new contenido();
        showContenido.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autorMessage;
    private javax.swing.JLabel autorValue;
    private javax.swing.JButton back;
    private javax.swing.JLabel calificacionMessage;
    private javax.swing.JSlider calificacionReseña;
    private javax.swing.JPanel categoriaContenido;
    private javax.swing.JLabel categoriaMessage;
    private javax.swing.JLabel categoriaValue;
    private javax.swing.JLabel comentariosMessage;
    private javax.swing.JButton contactarAutor;
    private javax.swing.JLabel descripcionMessage;
    private javax.swing.JLabel descripcionValue;
    private javax.swing.JLabel feedbackMessage;
    private javax.swing.JTextArea feedbackUser;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPanel2;
    private javax.swing.JLabel produccionMessage;
    private javax.swing.JLabel produccionValue;
    private javax.swing.JButton publicarContenido;
    private javax.swing.JTable tableReviews;
    private javax.swing.JLabel tituloValue;
    // End of variables declaration//GEN-END:variables
}
