package view;

import access.contenidoDAO;
import model.reseñaModel;
import access.reseñaDAO;
import access.usuarioDAO;
import java.util.ArrayList;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

public class feedback extends javax.swing.JFrame {

    public feedback() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Llenamos la pantalla con los valores de la variable publica
        tituloValue.setText(contenido.feedbackContenido.getTituloContenido());
        descripcionValue.setText(contenido.feedbackContenido.getDescripcionContenido());
        categoriaValue.setText(contenido.feedbackContenido.getCategoriaContenido());
        produccionValue.setText(contenido.feedbackContenido.getProduccionContenido());
        autorValue.setText(contenido.nombreAutor);
        
        // Mejoramos el aspecto de la calificacion
        calificacionReseña.setPaintTicks(true); // Las rayitas que marcan los números
        calificacionReseña.setMajorTickSpacing(1); // De cuanto en cuanto los números en el slider
        calificacionReseña.setPaintLabels(true);
        
        // Obtentemos el modelo la tabla donde iran las reseñas
        DefaultTableModel modelo = (DefaultTableModel) tableReviews.getModel();
        contenidoDAO idContent = new contenidoDAO();
        
        // Obtenemos el id del contenido con el cual obtenemos las reseñas
        int id = idContent.getIdContent(contenido.feedbackContenido.getTituloContenido(), contenido.feedbackContenido.getDescripcionContenido(), contenido.feedbackContenido.getCategoriaContenido(), contenido.feedbackContenido.getProduccionContenido());
        
        // Obtenemos toas las reseñas y las ponemos en la tabla con un for
        reseñaDAO reseña = new reseñaDAO();
        ArrayList<ArrayList> result = reseña.getAllReviews(id);
        
        if(result.isEmpty()){
            modelo.addRow(new Object[]{"Sin resultados", "Sin resultados", "Sin resultados"});
        } else {
            for(int i = 0; i < result.size(); i++){
                ArrayList<ArrayList> row = result.get(i);
                modelo.addRow(new Object[]{row.get(0), row.get(1), row.get(2)});
            }
        }
        
        /* Verificar si el usuario que ve el contenido es el mismo que lo publico */
        
        // Accedemos a los valores del contenido para saber quien es el autor mediante el id
        String titulo = contenido.feedbackContenido.getTituloContenido();
        String descripcion = contenido.feedbackContenido.getDescripcionContenido();
        String categoria = contenido.feedbackContenido.getCategoriaContenido();
        String produccion= contenido.feedbackContenido.getProduccionContenido();
        
        // Accedemos al id
        usuarioDAO usuario = new usuarioDAO();
        int idUsuarioContenido = usuario.getIdUser(titulo, descripcion, categoria, produccion);
        
        if(login.loginUser.getIdUsuario() == idUsuarioContenido){
            autorValue.setText("Tú");
            jScrollPanel2.setVisible(false);
            feedbackUser.setVisible(false);
            feedbackMessage.setVisible(false);
            calificacionMessage.setVisible(false);
            calificacionReseña.setVisible(false);
            publicarContenido.setVisible(false);
            contactarAutor.setVisible(false);
            
            descripcionValue.setSize(10, 20);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoriaContenido = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tituloValue = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        categoriaMessage = new javax.swing.JLabel();
        produccionMessage = new javax.swing.JLabel();
        autorMessage = new javax.swing.JLabel();
        descripcionMessage = new javax.swing.JLabel();
        jScrollPanel2 = new javax.swing.JScrollPane();
        feedbackUser = new javax.swing.JTextArea();
        feedbackMessage = new javax.swing.JLabel();
        publicarContenido = new javax.swing.JButton();
        contactarAutor = new javax.swing.JButton();
        comentariosMessage = new javax.swing.JLabel();
        categoriaValue = new javax.swing.JLabel();
        produccionValue = new javax.swing.JLabel();
        autorValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReviews = new javax.swing.JTable();
        calificacionReseña = new javax.swing.JSlider();
        calificacionMessage = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionValue = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        categoriaContenido.setBackground(new java.awt.Color(255, 255, 255));
        categoriaContenido.setMinimumSize(new java.awt.Dimension(1024, 520));
        categoriaContenido.setPreferredSize(new java.awt.Dimension(1024, 520));
        categoriaContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1024, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloValue.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        tituloValue.setForeground(new java.awt.Color(255, 255, 255));
        tituloValue.setText("Titulo contenido");
        jPanel2.add(tituloValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        back.setText("Volver");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel2.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, -1, -1));

        categoriaContenido.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 80));

        categoriaMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        categoriaMessage.setText("Categoria:");
        categoriaContenido.add(categoriaMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 20));

        produccionMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        produccionMessage.setText("Se trata de: ");
        categoriaContenido.add(produccionMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, 20));

        autorMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        autorMessage.setText("Autor: ");
        categoriaContenido.add(autorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, -1, 20));

        descripcionMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        descripcionMessage.setText("Descripcion");
        categoriaContenido.add(descripcionMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        feedbackUser.setColumns(20);
        feedbackUser.setLineWrap(true);
        feedbackUser.setRows(4);
        feedbackUser.setAutoscrolls(false);
        jScrollPanel2.setViewportView(feedbackUser);

        categoriaContenido.add(jScrollPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 408, 494, 96));

        feedbackMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        feedbackMessage.setText("Feedback");
        categoriaContenido.add(feedbackMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 386, -1, -1));

        publicarContenido.setText("Publicar");
        publicarContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                publicarContenidoMouseClicked(evt);
            }
        });
        categoriaContenido.add(publicarContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, -1, -1));

        contactarAutor.setText("Contactar");
        contactarAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactarAutorMouseClicked(evt);
            }
        });
        categoriaContenido.add(contactarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 440, -1, -1));

        comentariosMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        comentariosMessage.setText("Otros comentarios");
        categoriaContenido.add(comentariosMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

        categoriaValue.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        categoriaContenido.add(categoriaValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 157, 20));

        produccionValue.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        categoriaContenido.add(produccionValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 130, 20));

        autorValue.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        categoriaContenido.add(autorValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, 110, 20));

        tableReviews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Calificación", "Descipción", "Autor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableReviews);

        categoriaContenido.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 154, 420, 210));

        calificacionReseña.setMaximum(5);
        categoriaContenido.add(calificacionReseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 173, -1));

        calificacionMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        calificacionMessage.setText("Calificación");
        categoriaContenido.add(calificacionMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        descripcionValue.setEditable(false);
        jScrollPane2.setViewportView(descripcionValue);

        categoriaContenido.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 490, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoriaContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(categoriaContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contactarAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactarAutorMouseClicked
        
        reseñaDAO reseña = new reseñaDAO();
        usuarioDAO usuario = new usuarioDAO(); 
        
        // Accedemos a los valores del contenido para saber quien es el autor mediante el id
        String titulo = contenido.feedbackContenido.getTituloContenido();
        String descripcion = contenido.feedbackContenido.getDescripcionContenido();
        String categoria = contenido.feedbackContenido.getCategoriaContenido();
        String produccion= contenido.feedbackContenido.getProduccionContenido();
        
        // Accedemos al id
        int idUsuario = usuario.getIdUser(titulo, descripcion, categoria, produccion);
        
        // Verificamos que el usuario tenga permitido compartir su correo
        boolean pass = usuario.shareEmail(idUsuario);

        if(pass){
            // Obtenemos el correo
           String emailUser = reseña.getContactUser(idUsuario); 
           showMessageDialog(null, "El correo del usuaio es " + emailUser);    

        } else {
            showMessageDialog(null, "El usuario no tiene permitido compartir su contacto");    
        }
        
    }//GEN-LAST:event_contactarAutorMouseClicked

    private void publicarContenidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_publicarContenidoMouseClicked
        // Accedemos a los valores de los campos 
        String reseñaContenido = feedbackUser.getText();
        float calificacionContenido = calificacionReseña.getValue();
        
        // Accedemos a el id del contenido al cual le queremos hacer una reseña
        contenidoDAO idContent = new contenidoDAO();
        int id = idContent.getIdContent(contenido.feedbackContenido.getTituloContenido(), contenido.feedbackContenido.getDescripcionContenido(), contenido.feedbackContenido.getCategoriaContenido(), contenido.feedbackContenido.getProduccionContenido());
        
        // Creamos un nuevo modelo de reseña con la cual haremos una insercion en la base de datos
        reseñaModel reseña = new reseñaModel(calificacionContenido, reseñaContenido, id ,login.loginUser.getIdUsuario());
        reseñaDAO createReview = new reseñaDAO();
        
        // Insertamos la reseña en la base de datos
        createReview.createReview(reseña);
        
        // Eliminamos los registros que tengamos en la tabla
        DefaultTableModel modelo = (DefaultTableModel) tableReviews.getModel();
        int rowCount = modelo.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        
        // Volvemos a llamar a la tabla para que aparesca nuestra review
        reseñaDAO reseñaDAO = new reseñaDAO();
        ArrayList<ArrayList> result = reseñaDAO.getAllReviews(id);
        
        for(int i = 0; i < result.size(); i++){
            ArrayList<ArrayList> row = result.get(i);
            modelo.addRow(new Object[]{row.get(0), row.get(1), row.get(2)});
        }
        
        // Motramos un mensaje de que la reseña se creo correctamente
        showMessageDialog(null, "La reseña se creo correctamente");

    }//GEN-LAST:event_publicarContenidoMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        contenido showContenido = new contenido();
        showContenido.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autorMessage;
    private javax.swing.JLabel autorValue;
    private javax.swing.JButton back;
    private javax.swing.JLabel calificacionMessage;
    private javax.swing.JSlider calificacionReseña;
    private javax.swing.JPanel categoriaContenido;
    private javax.swing.JLabel categoriaMessage;
    private javax.swing.JLabel categoriaValue;
    private javax.swing.JLabel comentariosMessage;
    private javax.swing.JButton contactarAutor;
    private javax.swing.JLabel descripcionMessage;
    private javax.swing.JTextPane descripcionValue;
    private javax.swing.JLabel feedbackMessage;
    private javax.swing.JTextArea feedbackUser;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPanel2;
    private javax.swing.JLabel produccionMessage;
    private javax.swing.JLabel produccionValue;
    private javax.swing.JButton publicarContenido;
    private javax.swing.JTable tableReviews;
    private javax.swing.JLabel tituloValue;
    // End of variables declaration//GEN-END:variables
}
