package view;

import model.usuarioModel;
import access.usuarioDAO;
import java.util.ArrayList;

import static javax.swing.JOptionPane.showMessageDialog;
import org.apache.commons.codec.digest.DigestUtils;

public class login extends javax.swing.JFrame {
    
    // Creamos una variable publica del modelo del usuario con el cual identificaremos que usuario esta usando la sesion
    public static usuarioModel loginUser;
            
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        loginMessage = new javax.swing.JLabel();
        emailMessage = new javax.swing.JLabel();
        emailUser = new javax.swing.JTextField();
        passwordMessage = new javax.swing.JLabel();
        passwordUser = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        regsiterMessage = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Cuevana");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 0, -1, 520));

        loginMessage.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 36)); // NOI18N
        loginMessage.setText("Inicia Sesion");
        jPanel1.add(loginMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        emailMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        emailMessage.setText("Email");
        jPanel1.add(emailMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));
        jPanel1.add(emailUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 152, -1));

        passwordMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        passwordMessage.setText("Contraseña");
        jPanel1.add(passwordMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));
        jPanel1.add(passwordUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 152, -1));

        loginButton.setText("Entrar");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        regsiterMessage.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        regsiterMessage.setText("¿No tienes cuenta?");
        jPanel1.add(regsiterMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        registerButton.setText("Crear");
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        jPanel1.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        register reg = new register();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerButtonMouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // Obtenemos los valores de los campos
        String loginEmailUser = emailUser.getText();
        String loginPasswordUser = new String(passwordUser.getPassword());
        
        String loginPasswordEncripted = DigestUtils.md5Hex(loginPasswordUser);
        
        // Creamos un modelo de usuario solo con los valores que le pasamos 
        loginUser = new usuarioModel("", loginEmailUser, loginPasswordEncripted, false);
        usuarioDAO create = new usuarioDAO();
        
        // Consultamos si el usuario esta en la base de datos
        boolean pass = create.consultUser(loginUser);
        
        if(pass){
            // Accedemos a todos los valores del usuario que esta iniciando sesion y los agregamos a la variable publica 
            ArrayList<String> data = create.getUser(loginUser);
            
            System.out.println("Data login:");
            System.out.println("Id: " + data.get(0));            
            System.out.println("Name: " + data.get(1));
            System.out.println("Email: " + data.get(2));
            System.out.println("Password: " + data.get(3));
            System.out.println("Director: " + data.get(4));
            System.out.println("shareEmail: " + data.get(5));

            System.out.println("--------------------------------------------");
            
            loginUser.setIdUsuario( Integer.parseInt(data.get(0))  );
            loginUser.setNombreUsuario( data.get(1) );
            loginUser.setEmailUsuario( data.get(2) );
            loginUser.setContraseñaUsuario(loginPasswordUser);            
            loginUser.setDirectorUsuario( Integer.parseInt(data.get(4)) == 1 );
            loginUser.setShareEmail( Integer.parseInt(data.get(5)) == 1 );
            
            // Cargamos la pantalla principal
            contenido ingreso = new contenido();
            ingreso.setVisible(true);
            this.setVisible(false);
            
        } else {
            showMessageDialog(null, "El usuario no aparece en la base de datos, revise sus credenciales o cree una cuenta");
        }
    }//GEN-LAST:event_loginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emailMessage;
    private javax.swing.JTextField emailUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginMessage;
    private javax.swing.JLabel passwordMessage;
    private javax.swing.JPasswordField passwordUser;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel regsiterMessage;
    // End of variables declaration//GEN-END:variables
}
