package view;

import model.usuarioModel;
import access.usuarioDAO;
import static javax.swing.JOptionPane.showMessageDialog;
import org.apache.commons.codec.digest.DigestUtils;

public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        registerMessage = new javax.swing.JLabel();
        nameMessage = new javax.swing.JLabel();
        nameUser = new javax.swing.JTextField();
        emailMessage = new javax.swing.JLabel();
        emailUser = new javax.swing.JTextField();
        passwordMessage = new javax.swing.JLabel();
        passwordUser = new javax.swing.JPasswordField();
        directorUser = new javax.swing.JCheckBox();
        createUser = new javax.swing.JButton();
        loginMessage = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register - Cuevana");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 466, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 0, -1, 526));

        registerMessage.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 36)); // NOI18N
        registerMessage.setText("Registrate");
        jPanel1.add(registerMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        nameMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        nameMessage.setText("Nombre");
        jPanel1.add(nameMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));
        jPanel1.add(nameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 190, -1));

        emailMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        emailMessage.setText("Email");
        jPanel1.add(emailMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));
        jPanel1.add(emailUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 190, -1));

        passwordMessage.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        passwordMessage.setText("Contraseña");
        jPanel1.add(passwordMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));
        jPanel1.add(passwordUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 190, -1));

        directorUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        directorUser.setText("¿Eres creador?");
        jPanel1.add(directorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 190, -1));

        createUser.setText("Crear");
        createUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createUserMouseClicked(evt);
            }
        });
        jPanel1.add(createUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        loginMessage.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        loginMessage.setText("¿Ya tienes cuenta?");
        jPanel1.add(loginMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        loginButton.setText("Entrar");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        login log = new login();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginButtonMouseClicked

    private void createUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createUserMouseClicked
        // Accedemos a los valores que tienen los campos
        String nameNewUser = nameUser.getText();
        String emailNewUser = emailUser.getText();
        String passwordNewUser = passwordUser.getText();
        boolean isDirector = directorUser.isSelected();
        
        String passwordEncripted = DigestUtils.md5Hex(passwordNewUser);
        
        // Creamos un modelo usuario el cual vamos a insertar en la base de datos
        usuarioModel newUser = new usuarioModel(nameNewUser, emailNewUser, passwordEncripted, isDirector);
        usuarioDAO create = new usuarioDAO();
        
        create.insertUser(newUser);
        showMessageDialog(null, "Usuario creado correctamente");
        
        login log = new login();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_createUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createUser;
    private javax.swing.JCheckBox directorUser;
    private javax.swing.JLabel emailMessage;
    private javax.swing.JTextField emailUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginMessage;
    private javax.swing.JLabel nameMessage;
    private javax.swing.JTextField nameUser;
    private javax.swing.JLabel passwordMessage;
    private javax.swing.JPasswordField passwordUser;
    private javax.swing.JLabel registerMessage;
    // End of variables declaration//GEN-END:variables
}
